[package]
name = "dungeoncards"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.27"
strum_macros = "0.27"
rand = "0.9"
colored = "3.0"